from django.urls import re_path

from api.v1.v1_weather.views import (
    AdministrationCitizenScienceAPI,
    AdministrationLatestAPI,
    AdministrationNormalsAPI,
    AdministrationSeriesAPI,
    AdministrationStatsAPI,
    CitizenScienceExportAPI,
    CitizenScienceReadingDetailAPI,
    CitizenScienceReadingListAPI,
    CitizenScienceReminderAPI,
    CitizenScienceStationListAPI,
    WeatherSourceAPI,
    WeatherStationListAPI,
    WeatherStationMonthlyAPI,
)

urlpatterns = [
    re_path(
        r"^(?P<version>(v1))/weather/citizen-science/readings/"
        r"(?P<period>\d{4}-(0[1-9]|1[0-2]))",
        CitizenScienceReadingDetailAPI.as_view(),
        name="cs-reading-detail",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/citizen-science/readings",
        CitizenScienceReadingListAPI.as_view(),
        name="cs-reading-list",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/citizen-science/stations",
        CitizenScienceStationListAPI.as_view(),
        name="cs-stations",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/citizen-science/reminders",
        CitizenScienceReminderAPI.as_view(),
        name="cs-reminders",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/citizen-science/export",
        CitizenScienceExportAPI.as_view(),
        name="cs-export",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/administrations/"
        r"(?P<administration_id>[0-9]+)/citizen-science",
        AdministrationCitizenScienceAPI.as_view(),
        name="weather-administration-citizen-science",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/administrations/"
        r"(?P<administration_id>[0-9]+)/normals",
        AdministrationNormalsAPI.as_view(),
        name="weather-administration-normals",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/administrations/"
        r"(?P<administration_id>[0-9]+)/stats",
        AdministrationStatsAPI.as_view(),
        name="weather-administration-stats",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/administrations/"
        r"(?P<administration_id>[0-9]+)/series",
        AdministrationSeriesAPI.as_view(),
        name="weather-administration-series",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/stations/"
        r"(?P<wigos_id>[0-9A-Za-z-]+)/monthly",
        WeatherStationMonthlyAPI.as_view(),
        name="weather-station-monthly",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/stations",
        WeatherStationListAPI.as_view(),
        name="weather-stations",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/administrations/"
        r"(?P<administration_id>[0-9]+)/latest",
        AdministrationLatestAPI.as_view(),
        name="weather-administration-latest",
    ),
    re_path(
        r"^(?P<version>(v1))/weather/source",
        WeatherSourceAPI.as_view(),
        name="weather-source",
    ),
]
