# Generated by Django 4.2.16 on 2026-07-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField()),
                ("collection_id", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "weather_sources",
            },
        ),
        migrations.CreateModel(
            name="WeatherStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wigos_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("elevation_m", models.FloatField(blank=True, null=True)),
                (
                    "metadata_status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="v1_weather.weathersource",
                    ),
                ),
            ],
            options={
                "db_table": "weather_stations",
            },
        ),
        migrations.CreateModel(
            name="StationDailyAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("precipitation", "Precipitation"),
                            ("tmin", "Min temperature"),
                            ("tmax", "Max temperature"),
                            ("tmean", "Mean temperature"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.FloatField(null=True)),
                ("readings_count", models.IntegerField(default=0)),
                ("expected_count", models.IntegerField(default=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_values",
                        to="v1_weather.weatherstation",
                    ),
                ),
            ],
            options={
                "db_table": "weather_station_daily_aggregates",
            },
        ),
        migrations.AddConstraint(
            model_name="stationdailyaggregate",
            constraint=models.UniqueConstraint(
                fields=("station", "date", "parameter"),
                name="uniq_station_date_parameter",
            ),
        ),
    ]
