# Generated by Django 4.2.16 on 2026-07-17 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0003_administration_zone"),
        ("v1_weather", "0002_seed_default_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stationdailyaggregate",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("precipitation", "Precipitation"),
                    ("tmin", "Min temperature"),
                    ("tmax", "Max temperature"),
                    ("tmean", "Mean temperature"),
                    ("humidity", "Relative humidity"),
                    ("wind_speed", "Wind speed"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AdministrationNormal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("precipitation", "Precipitation"),
                            ("tmin", "Min temperature"),
                            ("tmax", "Max temperature"),
                            ("tmean", "Mean temperature"),
                            ("humidity", "Relative humidity"),
                            ("wind_speed", "Wind speed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.FloatField()),
                ("dataset", models.CharField(max_length=100)),
                ("pixel_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "administration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_normals",
                        to="v1_publication.administration",
                    ),
                ),
            ],
            options={
                "db_table": "weather_administration_normals",
            },
        ),
        migrations.AddConstraint(
            model_name="administrationnormal",
            constraint=models.UniqueConstraint(
                fields=("administration", "month", "parameter"),
                name="uniq_administration_month_parameter",
            ),
        ),
    ]
