# Generated by Django 4.2.16 on 2026-07-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0007_alter_administration_zone"),
        ("v1_weather", "0003_alter_stationdailyaggregate_parameter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenScienceReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.DateField()),
                ("min_temperature", models.FloatField(blank=True, null=True)),
                ("max_temperature", models.FloatField(blank=True, null=True)),
                ("precipitation", models.FloatField(blank=True, null=True)),
                ("soil_moisture", models.FloatField(blank=True, null=True)),
                ("soil_temperature", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citizen_science_readings",
                        to="v1_publication.administration",
                    ),
                ),
            ],
            options={
                "db_table": "citizen_science_readings",
            },
        ),
        migrations.AddConstraint(
            model_name="citizensciencereading",
            constraint=models.UniqueConstraint(
                fields=("administration", "year_month"),
                name="uniq_cs_reading_admin_month",
            ),
        ),
    ]
