# Generated by Django 4.2.16 on 2026-08-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_weather", "0004_citizensciencereading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrationnormal",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("precipitation", "Precipitation"),
                    ("tmin", "Min temperature"),
                    ("tmax", "Max temperature"),
                    ("tmean", "Mean temperature"),
                    ("humidity", "Relative humidity"),
                    ("wind_speed", "Wind speed"),
                    ("precip_3m_mean", "3-month precipitation mean"),
                    ("precip_3m_sd", "3-month precipitation SD"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="stationdailyaggregate",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("precipitation", "Precipitation"),
                    ("tmin", "Min temperature"),
                    ("tmax", "Max temperature"),
                    ("tmean", "Mean temperature"),
                    ("humidity", "Relative humidity"),
                    ("wind_speed", "Wind speed"),
                    ("precip_3m_mean", "3-month precipitation mean"),
                    ("precip_3m_sd", "3-month precipitation SD"),
                ],
                max_length=30,
            ),
        ),
    ]
