# Generated by Django 4.2.16 on 2026-08-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0009_administration_area_km2"),
        ("v1_weather", "0005_alter_administrationnormal_parameter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrationObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.DateField()),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("precipitation", "Precipitation"),
                            ("tmin", "Min temperature"),
                            ("tmax", "Max temperature"),
                            ("tmean", "Mean temperature"),
                            ("humidity", "Relative humidity"),
                            ("wind_speed", "Wind speed"),
                            ("precip_3m_mean", "3-month precipitation mean"),
                            ("precip_3m_sd", "3-month precipitation SD"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.FloatField()),
                ("dataset", models.CharField(max_length=100)),
                ("pixel_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "administration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="v1_publication.administration",
                    ),
                ),
            ],
            options={
                "db_table": "weather_administration_observations",
            },
        ),
        migrations.AddConstraint(
            model_name="administrationobservation",
            constraint=models.UniqueConstraint(
                fields=("administration", "year_month", "parameter"),
                name="uniq_administration_observation",
            ),
        ),
    ]
