# Generated by Django 4.2.16 on 2026-08-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_weather", "0006_add_administration_observation"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationdailyaggregate",
            name="is_seeded",
            field=models.BooleanField(default=False),
        ),
    ]
