# Generated by Django 4.2.16 on 2026-07-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("v1_publication", "0003_administration_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="IKSIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "iks_indicators",
            },
        ),
        migrations.CreateModel(
            name="KoboAdapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_url", models.URLField(max_length=255)),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
                ("last_sync_timestamp", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "kobo_adapters",
            },
        ),
        migrations.CreateModel(
            name="KoboForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("questions", models.JSONField(default=dict)),
                ("options", models.JSONField(default=dict)),
                ("languages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "kobo_forms",
            },
        ),
        migrations.CreateModel(
            name="KoboData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kobo_id", models.BigIntegerField(unique=True)),
                ("geo", models.JSONField(blank=True, null=True)),
                ("submission_time", models.DateTimeField()),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "instance_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="v1_iks.koboform",
                    ),
                ),
            ],
            options={
                "db_table": "kobo_data",
            },
        ),
        migrations.CreateModel(
            name="IKSValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kobo_id", models.BigIntegerField()),
                ("value", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "administration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iks_values",
                        to="v1_publication.administration",
                    ),
                ),
                (
                    "iks_indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="v1_iks.iksindicator",
                    ),
                ),
            ],
            options={
                "db_table": "iks_values",
            },
        ),
        migrations.AddField(
            model_name="iksindicator",
            name="kobo_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="v1_iks.koboform",
            ),
        ),
    ]
