# Generated by Django 4.2.16 on 2026-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_iks", "0003_koboadapter_single_active_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="koboform",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
