# Generated by Django 4.2.16 on 2025-01-24 09:07

import api.v1.v1_publication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Administration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "administrations",
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("year_month", models.DateField()),
                ("cdi_geonode_id", models.IntegerField(unique=True)),
                (
                    "initial_values",
                    models.JSONField(
                        validators=[api.v1.v1_publication.models.validate_json_values]
                    ),
                ),
                (
                    "validated_values",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[api.v1.v1_publication.models.validate_json_values],
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "In Review"),
                            (2, "In Validation"),
                            (3, "Published"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                ("narrative", models.TextField(blank=True, null=True)),
                (
                    "bulletin_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "publications",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "suggestion_values",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[api.v1.v1_publication.models.validate_json_values],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="v1_publication.publication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
            },
        ),
    ]
