# Generated by Django 4.2.16 on 2025-01-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_overdue_notified",
            field=models.BooleanField(default=False),
        ),
    ]
