# Generated by Django 4.2.16 on 2026-07-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0002_review_is_overdue_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("highveld", "Highveld"),
                    ("middleveld", "Middleveld"),
                    ("lowveld", "Lowveld"),
                    ("lubombo_plateau", "Lubombo_plateau"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
