# Generated by Django 4.2.16 on 2026-07-17 12:08

import api.v1.v1_publication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0003_administration_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationRaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator",
                    models.CharField(
                        choices=[
                            ("esi", "ESI percentile rank"),
                            ("evi2", "EVI2 percentile rank"),
                            ("sm", "SM percentile rank"),
                            ("spi", "SPI percentile rank"),
                        ],
                        max_length=10,
                    ),
                ),
                ("geonode_id", models.IntegerField()),
                (
                    "values",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[api.v1.v1_publication.models.validate_json_values],
                    ),
                ),
                ("extracted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rasters",
                        to="v1_publication.publication",
                    ),
                ),
            ],
            options={
                "db_table": "publication_rasters",
            },
        ),
        migrations.AddConstraint(
            model_name="publicationraster",
            constraint=models.UniqueConstraint(
                fields=("publication", "indicator"),
                name="uniq_publication_raster_indicator",
            ),
        ),
    ]
