# Generated by Django 4.2.16 on 2026-07-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0004_publicationraster_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationGeonode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geonode_id", models.IntegerField(unique=True)),
                ("category", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("year_month", models.DateField()),
                ("subtype", models.CharField(default="raster", max_length=20)),
                ("detail_url", models.URLField(blank=True, max_length=512, null=True)),
                ("embed_url", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=512, null=True),
                ),
                (
                    "download_url",
                    models.URLField(blank=True, max_length=512, null=True),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("resource_created", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "publication_geonodes",
                "indexes": [
                    models.Index(
                        fields=["category", "year_month"],
                        name="publication_categor_36760f_idx",
                    )
                ],
            },
        ),
    ]
