# Generated by Django 4.2.16 on 2026-07-22 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1_publication", "0005_publicationgeonode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Wet/normal conditions"),
                            (1, "D0 Abnormally Dry"),
                            (2, "D1 Moderate Drought"),
                            (3, "D2 Severe Drought"),
                            (4, "D3 Extreme Drought"),
                            (5, "D4 Exceptional Drought"),
                        ],
                        null=True,
                    ),
                ),
                ("reasoning", models.TextField(blank=True, null=True)),
                ("is_draft", models.BooleanField(default=True)),
                ("majority_category", models.IntegerField(blank=True, null=True)),
                ("is_override", models.BooleanField(default=False)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_decisions",
                        to="v1_publication.administration",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_decisions",
                        to="v1_publication.publication",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "validation_decisions",
            },
        ),
        migrations.AddConstraint(
            model_name="validationdecision",
            constraint=models.UniqueConstraint(
                fields=("publication", "administration"),
                name="uniq_validation_decision_per_inkhundla",
            ),
        ),
    ]
