# Generated by Django 4.2.16 on 2026-07-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0006_validationdecision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administration",
            name="zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("highveld", "Highveld"),
                    ("upper_middleveld", "Upper Middleveld"),
                    ("lower_middleveld", "Lower Middleveld"),
                    ("western_lowveld", "Western Lowveld"),
                    ("eastern_lowveld", "Eastern Lowveld"),
                    ("lubombo_range", "Lubombo Range"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
