# Generated by Django 4.2.16 on 2026-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0008_briefforwardlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="area_km2",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
