# Generated by Django 4.2.16 on 2026-08-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0009_administration_area_km2"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="is_seeded",
            field=models.BooleanField(default=False),
        ),
    ]
