# Generated by Django 4.2.16 on 2026-08-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0010_publication_is_seeded"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="sector_context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
