# Generated by Django 4.2.16 on 2025-01-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="technical_working_group",
            field=models.IntegerField(
                choices=[
                    (1, "NDMA (National Disaster Management Agency)"),
                    (2, "MoAg (Ministry of Agriculture)"),
                    (3, "MET (Meteorological Office)"),
                    (4, "DWA (Department of Water Affairs)"),
                    (5, "UNESWA (University of Eswatini)"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
