# Generated by Django 4.2.16 on 2025-01-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0002_systemuser_technical_working_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(1, "Admin"), (2, "Reviewer")], default=2
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("conditions", models.JSONField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("role", "action", "subject")},
            },
        ),
    ]
