# Generated by Django 4.2.16 on 2025-02-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0003_ability"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ability",
            table="ability",
        ),
    ]
