# Generated by Django 4.2.16 on 2026-07-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0004_alter_ability_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="activity_sector",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
