# Generated by Django 4.2.16 on 2026-07-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0005_systemuser_activity_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="activity_sector",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Food & Agriculture"),
                    (2, "Health & Nutrition"),
                    (3, "Water & Sanitation"),
                    (4, "Education"),
                    (5, "Environment & Energy"),
                    (6, "Coordination"),
                    (7, "Social Protection"),
                    (8, "Transport & Logistics"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
