# Generated by Django 4.2.16 on 2026-07-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1_publication", "0007_alter_administration_zone"),
        ("v1_users", "0007_alter_systemuser_technical_working_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="administration",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observers",
                to="v1_publication.administration",
            ),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="station_name",
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="station_sensors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="station_type",
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="ability",
            name="role",
            field=models.IntegerField(
                choices=[(1, "Admin"), (2, "Reviewer"), (3, "Observer")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="role",
            field=models.IntegerField(
                choices=[(1, "Admin"), (2, "Reviewer"), (3, "Observer")], default=2
            ),
        ),
        migrations.AddConstraint(
            model_name="systemuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("role", 3)),
                fields=("administration",),
                name="uniq_observer_per_administration",
            ),
        ),
    ]
