# Generated by Django 4.2.16 on 2026-09-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0009_systemuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="manages_citizen_science",
            field=models.BooleanField(
                default=False,
                help_text="Can manage citizen-science stations and observers, without being an admin.",
            ),
        ),
    ]
