# Generated by Django 4.2.16 on 2026-09-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0010_systemuser_manages_citizen_science"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="technical_working_group",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "NDRMA (National Disaster Risk Management Authority)"),
                    (2, "MoAg (Ministry of Agriculture)"),
                    (3, "MET (Meteorological Office)"),
                    (4, "DWA (Department of Water Affairs)"),
                    (5, "UNESWA (University of Eswatini)"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
