from django.urls import re_path
from api.v1.v1_iks.views import (
    IKSStatsView,
    IKSSeriesView,
    IKSDownloadMonthlyView,
    IKSIndicatorsListView,
    IKSNetSignalAggregationView,
    IKSIndicatorCountsAggregationView,
    IKSAgreementAggregationView,
    IKSHeatmapAggregationView,
    IKSSoilTrendAggregationView,
    IKSAdministrationListView,
    IKSPhotosView,
)

urlpatterns = [
    re_path(
        r"^(?P<version>(v1))/iks/(?P<administration_id>[0-9]+)/stats$",
        IKSStatsView.as_view(),
        name="iks-stats",
    ),
    re_path(
        r"^(?P<version>(v1))/iks/(?P<administration_id>[0-9]+)/series$",
        IKSSeriesView.as_view(),
        name="iks-series",
    ),
    re_path(
        r"^(?P<version>(v1))/iks/download/monthly$",
        IKSDownloadMonthlyView.as_view(),
        name="iks-download-monthly",
    ),
    re_path(
        r"^(?P<version>(v1))/iks/indicators$",
        IKSIndicatorsListView.as_view(),
        name="iks-indicators",
    ),
    re_path(
        r"^(?P<version>(v1))/iks/aggregations/net-signal$",
        IKSNetSignalAggregationView.as_view(),
        name="iks-net-signal-aggregation",
    ),
    re_path(
        r"^(?P<version>(v1))/iks/aggregations/indicator-counts$",
        IKSIndicatorCountsAggregationView.as_view(),
        name="iks-indicator-counts-aggregation",
    ),
    re_path(
        r"^(?P<version>(v1))/iks/aggregations/agreement$",
        IKSAgreementAggregationView.as_view(),
        name="iks-agreement-aggregation",
    ),
    re_path(
        r"^(?P<version>(v1))/iks/aggregations/heatmap$",
        IKSHeatmapAggregationView.as_view(),
        name="iks-heatmap-aggregation",
    ),
    re_path(
        r"^(?P<version>(v1))/iks/aggregations/soil-trend$",
        IKSSoilTrendAggregationView.as_view(),
        name="iks-soil-trend-aggregation",
    ),
    re_path(
        r"^(?P<version>(v1))/iks/administrations$",
        IKSAdministrationListView.as_view(),
        name="iks-administrations",
    ),
    re_path(
        r"^(?P<version>(v1))/iks/(?P<administration_id>[0-9]+)/photos$",
        IKSPhotosView.as_view(),
        name="iks-photos",
    ),
]
