import json
from django.core.management import BaseCommand
from django.conf import settings
from jsmin import jsmin

from api.v1.v1_publication.constants import AdministrationZones


class Command(BaseCommand):
    def handle(self, *args, **options):
        with open("source/eswatini.topojson") as f:
            topojson = json.load(f)

        # Inject the agro-ecological `zone` per Inkhundla (region already lives
        # in the topojson). Values are the AdministrationZones slugs, matching
        # Administration.zone — source/climatic-zones.json is generated by
        # `assign_administration_zones`, not hand-maintained.
        with open("source/climatic-zones.json") as f:
            zones = {
                z["administration_id"]: z.get("zone")
                for z in json.load(f)
            }
        for obj in topojson.get("objects", {}).values():
            for geom in obj.get("geometries", []):
                props = geom.get("properties", {})
                props["zone"] = zones.get(props.get("administration_id"))

        # The zone vocabulary rides along on the same script, so the frontend
        # reads it off `window.zones` instead of keeping its own copy — that
        # copy had drifted to four zones while the layer defines six.
        zone_options = [
            {"value": value, "label": label}
            for value, label in AdministrationZones.choices()
        ]

        min_config = jsmin(
            "".join(
                [
                    "var topojson=",
                    json.dumps(topojson),
                    ";var zones=",
                    json.dumps(zone_options),
                    ";",
                ]
            )
        )
        open("source/config/config.min.js", "w").write(min_config)
        if not settings.TEST_ENV:
            self.stdout.write(self.style.SUCCESS(
                "config.js successfully generated!"
            ))  # pragma: no cover
