# Generated by Django 4.2.16 on 2025-02-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_rundeck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="job_config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
