# Generated by Django 4.2.16 on 2025-04-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_rundeck", "0002_settings_job_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="lst_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="ndvi_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="sm_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="spi_weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
