# Generated by Django 4.2.16 on 2026-07-21 04:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("v1_publication", "0004_publicationraster_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("population", models.PositiveIntegerField(default=0)),
                ("under_five", models.PositiveIntegerField(default=0)),
                ("cropland_ha", models.PositiveIntegerField(default=0)),
                (
                    "rainfed_share",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("livestock", models.PositiveIntegerField(default=0)),
                ("rangeland", models.PositiveIntegerField(default=0)),
                ("boreholes", models.PositiveIntegerField(default=0)),
                ("taps", models.PositiveIntegerField(default=0)),
                (
                    "v_ipc",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "v_prep",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("source", models.CharField(default="placeholder", max_length=255)),
                ("as_of", models.DateField(blank=True, null=True)),
                ("is_placeholder", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "administration",
                    models.OneToOneField(
                        db_column="administration_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator",
                        to="v1_publication.administration",
                    ),
                ),
            ],
            options={
                "db_table": "indicator",
            },
        ),
        migrations.AddConstraint(
            model_name="indicator",
            constraint=models.UniqueConstraint(
                fields=("administration",), name="uniq_indicator_per_administration"
            ),
        ),
        migrations.AddConstraint(
            model_name="indicator",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("rainfed_share__gte", 0.0), ("rainfed_share__lte", 1.0)
                ),
                name="ck_indicator_rainfed_share_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="indicator",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("v_ipc__gte", 0.0),
                    ("v_ipc__lte", 1.0),
                    ("v_prep__gte", 0.0),
                    ("v_prep__lte", 1.0),
                ),
                name="ck_indicator_vuln_unit",
            ),
        ),
    ]
