# Generated by Django 4.2.16 on 2026-07-27 11:48

import django.core.validators
from django.db import migrations, models


def migrate_data_forward(apps, schema_editor):
    Indicator = apps.get_model("v1_indicators", "Indicator")
    for ind in Indicator.objects.all():
        # Copy livestock count to cattle
        if hasattr(ind, "livestock"):
            ind.cattle = getattr(ind, "livestock", None)

        # Copy cropland_ha count to rainfed_cropland
        if hasattr(ind, "cropland_ha"):
            ind.rainfed_cropland = getattr(ind, "cropland_ha", 0)

        # Map v_ipc float -> ipc_phase int (1..5)
        v_ipc = getattr(ind, "v_ipc", 0.0) or 0.0
        if v_ipc > 0.0:
            if v_ipc <= 0.15:
                ind.ipc_phase = 1
            elif v_ipc <= 0.45:
                ind.ipc_phase = 2
            elif v_ipc <= 0.72:
                ind.ipc_phase = 3
            elif v_ipc <= 0.92:
                ind.ipc_phase = 4
            else:
                ind.ipc_phase = 5

        ind.save()


def migrate_data_backward(apps, schema_editor):
    Indicator = apps.get_model("v1_indicators", "Indicator")
    for ind in Indicator.objects.all():
        if ind.cattle is not None:
            ind.livestock = ind.cattle
        ind.cropland_ha = ind.rainfed_cropland
        if ind.ipc_phase:
            # Reverse band map to middle float values
            rev_map = {1: 0.10, 2: 0.30, 3: 0.60, 4: 0.85, 5: 1.00}
            ind.v_ipc = rev_map.get(ind.ipc_phase, 0.0)
        ind.save()


class Migration(migrations.Migration):

    dependencies = [
        ("v1_indicators", "0001_initial"),
    ]

    operations = [
        # 1. Remove old constraints
        migrations.RemoveConstraint(
            model_name="indicator",
            name="ck_indicator_rainfed_share_unit",
        ),
        migrations.RemoveConstraint(
            model_name="indicator",
            name="ck_indicator_vuln_unit",
        ),
        # 2. Add new fields
        migrations.AddField(
            model_name="indicator",
            name="land_use_dvi_agri",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="cattle",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="water_demand",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="ipc_phase",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="elderly",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="indicator",
            name="rainfed_cropland",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="population",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        # 3. Data bridge
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
        # 4. Remove old fields
        migrations.RemoveField(
            model_name="indicator",
            name="rainfed_share",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="v_ipc",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="v_prep",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="cropland_ha",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="livestock",
        ),
        # 5. Add new constraints
        migrations.AddConstraint(
            model_name="indicator",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("land_use_dvi_agri__isnull", True),
                    models.Q(
                        ("land_use_dvi_agri__gte", 0.0),
                        ("land_use_dvi_agri__lte", 1.0),
                    ),
                    _connector="OR",
                ),
                name="ck_indicator_dvi_agri_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="indicator",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("ipc_phase__isnull", True),
                    models.Q(("ipc_phase__gte", 1), ("ipc_phase__lte", 5)),
                    _connector="OR",
                ),
                name="ck_indicator_ipc_phase_range",
            ),
        ),
    ]
