# Generated by Django 4.2.16 on 2026-08-25 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1_indicators", "0002_risk_model_v2"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.CharField(db_index=True, max_length=64)),
                ("origin", models.CharField(default="upload", max_length=16)),
                ("file", models.FileField(upload_to="datasets/%Y/%m/")),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("source_label", models.CharField(max_length=255)),
                ("as_of", models.DateField()),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Rejected"),
                            (2, "Validated"),
                            (3, "Applied"),
                            (4, "Superseded"),
                            (5, "Discarded"),
                        ],
                        default=2,
                    ),
                ),
                ("report", models.JSONField(default=dict)),
                ("geonode_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_dataset_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dataset_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dataset_uploads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dataset", "-created_at"],
                        name="dataset_upl_dataset_c705b8_idx",
                    )
                ],
            },
        ),
    ]
