# Generated by Django 4.2.16 on 2025-01-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="type",
            field=models.IntegerField(
                choices=[(1, "test"), (2, "verification_email"), (3, "forgot_password")]
            ),
        ),
    ]
