# Generated by Django 4.2.16 on 2025-01-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_jobs", "0002_alter_jobs_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "test"),
                    (2, "verification_email"),
                    (3, "forgot_password"),
                    (4, "review_completed"),
                ]
            ),
        ),
    ]
