# Generated by Django 4.2.16 on 2026-07-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_jobs", "0008_alter_jobs_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "test"),
                    (2, "verification_email"),
                    (3, "forgot_password"),
                    (4, "review_completed"),
                    (5, "review_request"),
                    (6, "initial_cdi_values"),
                    (7, "download_geonode_dataset"),
                    (8, "new_user_password_setup"),
                    (9, "send_feedback"),
                    (10, "indicator_values"),
                    (11, "attach_component_rasters"),
                    (12, "cs_reminder"),
                    (13, "cs_magic_link"),
                ]
            ),
        ),
    ]
