# Generated by Django 4.2.16 on 2026-07-08 06:41

import api.v1.v1_activity.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "sector",
                    models.IntegerField(
                        choices=[
                            (1, "Food & Agriculture"),
                            (2, "Health & Nutrition"),
                            (3, "Water & Sanitation"),
                            (4, "Education"),
                            (5, "Environment & Energy"),
                            (6, "Coordination"),
                            (7, "Social Protection"),
                            (8, "Transport & Logistics"),
                        ]
                    ),
                ),
                (
                    "triggers",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[
                            api.v1.v1_activity.validators.validate_triggers
                        ],
                    ),
                ),
                (
                    "owner",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "coord_with",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "response_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Public"), (2, "Institutional")],
                        null=True,
                    ),
                ),
                (
                    "source_doc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("version", models.CharField(default="v1.0", max_length=20)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Draft"), (2, "Active"), (3, "Archived")],
                        default=1,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activated_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "response_activities",
            },
        ),
        migrations.CreateModel(
            name="ActivitySignOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signoffs",
                        to="v1_activity.responseactivity",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_signoffs_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_signoffs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_signoffs",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Draft"), (2, "Active"), (3, "Archived")],
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Draft"), (2, "Active"), (3, "Archived")],
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="v1_activity.responseactivity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_history",
                "ordering": ["created_at"],
            },
        ),
    ]
