# Generated by Django 4.2.16 on 2026-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="responseactivity",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
